language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
env:
  - TESTFOLDER=data_platform
  - TESTFOLDER=data_fetcher
script:
  - flake8 $TESTFOLDER
  - pylint $TESTFOLDER
  - mypy $TESTFOLDER
